---
- name: Ansible playbook for login to openshift
  remote_user: root
  hosts: webservers
  tasks:
     - name: Logging in to OpenShift cluster
       command: oc login https://10.20.14.183:8443/ -u system -p admin
     - name: Printing BUILD Number
       debug: msg="Hello to {{BUILD_NUMBER}}, from Ansible!!"
     - name: Setting respective project - [webapp]
       command: oc project webapp
     - name: Processing deployment templaate
       shell: oc process -f openshift_deployment.json APP_ENV=DEV APP_NAME=simplewebapp IMAGE_NAME=simplewebapp:6.0 SERVICE_NAME=simplewebapp > resources.yml
       args:
         chdir: Java-web-app/
     - name: Applying deployment template
       command: oc apply -f resources.yml
       args:
         chdir: Java-web-app/
...
