---
- name: Ansible playbook for login to openshift
  remote_user: root
  hosts: webservers
  tasks:
     - name: Create Project
       command: oc login https://10.20.14.183:8443/ -u system -p admin
     - name: Changing webapp project
       command: oc project webapp
     - name: New app creating
       command: oc process -f template.yaml | oc apply -f -
     - name: Exposing Service
       command: oc expose service/simplejavawebapp
...
