---
- name: Ansible playbook for login to openshift
  remote_user: root
  hosts: webservers
  tasks:
     - name: Create Project
       command: oc login https://10.20.14.183:8443/ -u system -p admin
     - name: Changing webapp project
       command: oc project webapp
     - name: Deploying application into openshift
       command: oc process -f openshift_deployment.json `cat Simple-Web-App-Parameters.DEV` | oc apply -f -
     - name: Exposing Service
       command: oc expose service/simplejavawebapp
...
