---
- name: Ansible playbook for Openshift Deployment
  hosts: webservers
  tasks:
     - name: Pulling latest code from Git repo
       command: git pull https://github.com/harshalpanditxoriant/Java-web-app.git master
       become: yes
       become_user: root
       args:
         chdir: Java-web-app/
     - name: Building Docker Image with Tag number {{BUILD_NUMBER}}.0
       command: docker build -t simplewebapp:{{BUILD_NUMBER}}.0 .
       become: yes
       become_user: root
       args:
         chdir: Java-web-app/
     - name: Login into OpenShift cluster
       command: oc login https://10.20.14.183:8443/ -u system -p admin
     - name: configuring project - [webapp]
       command: oc project webapp
     - name: Processing deployment templaate and input parameters
       shell: oc process -f openshift_deployment.json IMAGE_NAME=simplewebapp:{{BUILD_NUMBER}}.0 APP_ENV=DEV > resources.yml
       args:
         chdir: Java-web-app/
     - name: Applying deployment template and deploying code into openshift
       command: oc apply -f resources.yml
       args:
         chdir: Java-web-app/
...
