apiVersion: v1
kind: DeploymentConfig
metadata:
  name: simplejavawebapp
  namespace: webapp
  selfLink: /oapi/v1/namespaces/webapp/deploymentconfigs/simplejavawebapp
  uid: f234081e-9673-11ea-b565-fa163e8a1b4f
  resourceVersion: '40391968'
  generation: 2
  creationTimestamp: '2020-05-15T06:18:51Z'
  labels:
    app: simplejavawebapp
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - simplejavawebapp
        from:
          kind: ImageStreamTag
          namespace: webapp
          name: 'simplejavawebapp:latest'
        lastTriggeredImage: >-
          172.30.248.78:5000/webapp/simplejavawebapp@sha256:33fdfd4d0503d670cec5c420543d0d87abaf4c58ad82c75a1df1f97dc0cfb991
  replicas: 1
  test: false
  selector:
    app: simplejavawebapp
    deploymentconfig: simplejavawebapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplejavawebapp
        deploymentconfig: simplejavawebapp
      annotations:
        openshift.io/container.simplejavawebapp.image.entrypoint: '["catalina.sh","run"]'
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: simplejavawebapp
          image: >-
            172.30.248.78:5000/webapp/simplejavawebapp@sha256:33fdfd4d0503d670cec5c420543d0d87abaf4c58ad82c75a1df1f97dc0cfb991
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 1
  observedGeneration: 2
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: webapp
            name: 'simplejavawebapp:latest'
  conditions:
    - type: Available
      status: 'True'
      lastTransitionTime: '2020-05-15T06:19:31Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastTransitionTime: '2020-05-15T06:19:28Z'
      reason: NewReplicationControllerAvailable
      message: Replication controller "simplejavawebapp-1" has completed progressing
